### PR TITLE
`package.json` fixes

### PR DESCRIPTION
**Pull request by FilipChalupa**

### CODE REVIEW

**Review by noamr — APPROVED** [review]

**Comment by FilipChalupa** [comment]
@noamr, can you please `npm publish` new version?

**Comment by noamr** [comment]
> @noamr, can you please `npm publish` new version?

Done

**Comment by FilipChalupa** [comment]
I'm terribly sorry that I've missed that source files are needed too. 🤦‍♀️ Here is a fix. https://github.com/noamr/use-view-transitions/pull/3

**Comment by noamr** [comment]
> I'm terribly sorry that I've missed that source files are needed too. 🤦‍♀️ Here is a fix. #3

Thanks for your contributions! I was wondering what you're using this library for.
I set up Github actions now so publishing should be smoother.

**Comment by FilipChalupa** [comment]
> I was wondering what you're using this library for.

Right know I'm just experimenting. Trying to understand how view transitions work. 🙂

**Comment by FilipChalupa** [comment]
> I set up Github actions now so publishing should be smoother.

Nice.

**Pull request merged**
