### PR TITLE
GitHub pages examples + mood picker example

### PR DESCRIPTION
**Pull request by FilipChalupa**
Before merging please activate GitHub pages https://github.com/noamr/use-view-transitions/settings/pages

image

### CODE REVIEW

**Comment by FilipChalupa** [comment]
There is a known issue which I'm not able to debug since I don't know what `suspendViewTransitionCapture` and `resumeViewTransitionCapture` are solving. The emoji incorrectly crossfades without any other movement.

### ❌ Current state with library usage but broken

image

crossfade

### ✅ Expected but with native `startViewTransition` (without library)

image

native

**Comment by noamr** [comment]
> There is a known issue which I'm not able to debug since I don't know what `suspendViewTransitionCapture` and `resumeViewTransitionCapture` are solving. The emoji incorrectly crossfades without any other movement.

I think for something this simple you probably don't need this library and the `flushSync` method would work :)
But I need to debug to understand why this example doesn't work. Will get back to you, and thanks for contributing all this!

**Review by noamr — APPROVED** [review]

**Comment by FilipChalupa** [comment]
> for something this simple you probably don't need this library

I agree. I wish to use the library for next.js navigation later. 🙂

**Comment by FilipChalupa** [comment]
Please don't forget to active GitHub pages as described above to solve the CI error.

image

**Comment by noamr** [comment]
> > There is a known issue which I'm not able to debug since I don't know what `suspendViewTransitionCapture` and `resumeViewTransitionCapture` are solving. The emoji incorrectly crossfades without any other movement.
> 
> I think for something this simple you probably don't need this library and the `flushSync` method would work :) But I need to debug to understand why this example doesn't work. Will get back to you, and thanks for contributing all this!

There was a spurious `resolve()` that created this bug. I wish there was a good way to e2e-test this, if you have any thoughts.

**Comment by FilipChalupa** [comment]
Nice catch 👀

**Comment by FilipChalupa** [comment]
> wish there was a good way to e2e-test this

First thing that came to my mind is [Playwright video capture](https://playwright.dev/docs/videos). But I worry it can do pixel diffing in picture mode only.

**Comment by noamr** [comment]
@FilipChalupa btw your mood selector example is very nice! But something about it can be improved. It over-captures: as in, some elements have transition names but don't end up transitioning. In a bigger page that can feel laggy. Do you want to take a stab at it?

**Pull request merged**
